<?php $post = $this->getPost(); ?>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="postWrapper">
    <div class="post-h-info">
        <div class="date">
            <?php
            $_ct= new Zend_Date($post->getCreatedTime());
            ?>
            <span class="month"><?php echo $_ct->toString('MMM'); ?></span>
            <span class="day"><?php echo $_ct->toString('dd'); ?></span>
            <span class="year"><?php echo $_ct->toString('y'); ?></span>
        </div>
        <div class="author">
            <label><?php echo $this->__("Post By"); ?></label>
            <span><?php echo $post->getUser(); ?></span>
        </div>
        <?php if ($this->getCommentsEnabled() && 1==0 ): ?>
        <div class="cmt">
            <?php echo $post->getCommentCount(); ?> <a href="<?php echo $post->getAddress(); ?>#commentBox" >Comments</a>
        </div>
        <?php endif; ?>
    </div>
    <div class="content-inner">
        <div class="postTitle title-detail">
            <h2><?php echo $post->getTitle(); ?></h2>
        </div>

        <div class="postContent">
            <?php echo $post->getPostContent(); ?>
            <!-- AddThis Button BEGIN -->
            <div class="addthis_toolbox addthis_default_style ">
            <a class="addthis_button_facebook_like" fb:like:layout="button_count"></a>
            <a class="addthis_button_tweet"></a>
            <a class="addthis_button_pinterest_pinit" pi:pinit:layout="horizontal"></a>
            <a class="addthis_counter addthis_pill_style"></a>
            </div>
            <script type="text/javascript">var addthis_config = {"data_track_addressbar":true};</script>
            <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-507b2455057cfd5f"></script>
            <!-- AddThis Button END -->
        </div>
        <?php echo $this->getBookmarkHtml($post) ?>
    </div>
    <div class="post-info clearfix">
        <div class="tags"><?php echo Mage::getBlockSingleton('blog/blog')->getTagsHtml($post) ?></div>
        <div class="postDetails">
            <?php $postCats = $post->getCats(); ?>
            <?php if (!empty($postCats)): ?>
                <h4><?php echo Mage::helper('blog')->__('Posted in:'); ?></h4>
                <?php foreach ($postCats as $title => $url): ?>
                    <a href="<?php echo $url; ?>"><?php echo $title; ?></a> 
                <?php endforeach; ?> 
            <?php else: ?>
                <?php echo Mage::helper('blog')->__('Posted'); ?>
            <?php endif; ?>
        </div>
    </div>


    <!-- Comment Section -->

    <?php if ($this->getCommentsEnabled()): ?>
        <?php $comments = $this->getComment(); ?>
        <?php
        if(count($comments) > 0){?>
        <div class="postTitle cmt-heading">
            <h2><?php echo $this->__('Comments') ?></h2>
        </div>
        <?php
        } ?>
        <?php //echo $this->getChildHtml('aw_blog_comments_toolbar'); ?>
            <?php foreach ($comments as $comment) : ?>
                <div class="commentWrapper">
                    <div class="commentDetails"><h4 class="username"><?php echo $comment->getUser(); ?></h4> <?php echo $this->__("posted on") ?> <?php echo $this->formatDate($comment->getCreatedTime(), Mage::getStoreConfig('blog/blog/dateformat'), true); ?></div>
                    <div class="commentContent"><?php echo nl2br($comment->getComment()); ?></div>
                </div>       
            <?php endforeach; ?>
        <div class="blog-toolbar post">
         <?php echo $this->getChildHtml('aw_blog_comments_toolbar'); ?>
        </div>
     

        <?php if ($post->getComments()): ?>
            <div class="postError"><?php echo Mage::helper('blog')->__('Comments are Closed for this post') ?></div>
        <?php else: ?>
            <?php if ($this->getLoginRequired()): ?>
                <?php if ($this->helper('customer')->isLoggedIn()): ?>
                    <form action="" id="postComment" method="post">  
                        <fieldset class="group-select">
                            <h4 class="legend"><?php echo Mage::helper('blog')->__('Submit Comment') ?></h4>
                            <ul class="form-list">
                                <li>

                                    <div class="input-box aw-blog-comment-area">
                                        <label for="comment" class="required"><?php echo Mage::helper('blog')->__('Comment') ?><em>*</em></label><br />
                                        <textarea name="comment" id="comment" title="<?php echo $this->__('Comment') ?>" class="required-entry input-text" style="height:150px;width:95%;" cols="50" rows="5"><?php echo $this->getCommentText(); ?></textarea>
                                    </div>
                                </li>
                            </ul>
                        </fieldset>
                        <div class="button-set" style="width:96%">
                            <input name="post_id" type="hidden" value="<?php echo $post->getPostId(); ?>" />
                            <input name="email" type="hidden" value="<?php echo $this->htmlEscape($this->helper('blog')->getUserEmail()) ?>"/>
                            <input name="user" type="hidden" value="<?php echo $this->htmlEscape($this->helper('blog')->getUserName()) ?>"/>
                            <p class="required"><?php echo $this->__('* Required Fields') ?></p>
                            <button class="form-button button" type="submit"><span><span><?php echo Mage::helper('blog')->__('Submit Comment') ?></span></span></button>
                        </div>
                    </form>

                    <script type="text/javascript">
                        var contactForm = new VarienForm('postComment', false);
                    </script>            

                <?php else: ?>
                    <p><?php echo Mage::helper('blog')->__('You must be logged in to post a comment.'); ?></p>
                    <p><a href="<?php echo Mage::helper('customer')->getLoginUrl(); ?>"><?php echo Mage::helper('blog')->__('click here'); ?></a> <?php echo Mage::helper('blog')->__('to log in'); ?></p>
                <?php endif ?>

            <?php else: ?>

                <form action="" id="postComment" method="post">
                    <fieldset class="group-select">
                        <h4 class="legend"><?php echo Mage::helper('blog')->__('Submit Comment') ?></h4>
                        <ul class="form-list row-fluid">
                            <li class="span12">
                                <div class="input-box cmt-user">
                                    <label for="user" class="required"><?php echo Mage::helper('blog')->__('Name') ?><em>*</em></label>
                                    <input name="user" id="user" value="<?php echo $this->getCommentName(); ?>" placeholder="<?php echo Mage::helper('blog')->__('Name') ?> (*)"  title="<?php echo $this->__('Name') ?>" class="required-entry input-text" type="text" />
                                </div>
                                <div class="input-box cmt-email">
                                    <label for="email" class="required"><?php echo Mage::helper('blog')->__('Email') ?><em>*</em></label>
                                    <input name="email" id="email" value="<?php echo $this->getCommentEmail(); ?>" title="<?php echo $this->__('Email') ?>" placeholder="<?php echo Mage::helper('blog')->__('Email') ?> (*)"  class="required-entry input-text validate-email" type="text" />
                                </div>
                                <?php
                                if (Mage::getStoreConfig('blog/recaptcha/enabled') && !$this->helper('customer')->isLoggedIn()) {
                                    require_once 'recaptcha/recaptchalib-aw.php';
                                    // Get a key from http://recaptcha.net/api/getkey
                                    $publickey = Mage::getStoreConfig('blog/recaptcha/publickey');
                                    $privatekey = Mage::getStoreConfig('blog/recaptcha/privatekey');
                                    $error = null;
                                    echo recaptcha_get_html($publickey, $error);
                                }
                                ?>
                            </li>
                            <li class="span12">
                                <div class="input-box aw-blog-comment-area">
                                    <textarea name="comment" id="comment" placeholder="<?php echo Mage::helper('blog')->__('Comment') ?> (*)"  title="<?php echo Mage::helper('blog')->__('Comment') ?>" class="required-entry input-text" style="height:180px;width:95%;" cols="50" rows="5"><?php echo $this->getCommentText(); ?></textarea>
                                </div>
                            </li>
                        </ul>
                        <div class="button-set">
                            <button class="button form-button" type="submit"><span><span><?php echo Mage::helper('blog')->__('Submit Comment') ?></span></span></button>
                        </div>
                        <input name="post_id" type="hidden" value="<?php echo $post->getPostId(); ?>" />
                    </fieldset>
                </form>
                <script type="text/javascript">
                    var contactForm = new VarienForm('postComment', false);
                </script>
            <?php endif; ?>
        <?php endif; ?>
    <?php endif; ?>
</div>